[build-system]
requires = [
    "scikit_build_core[pyproject]",
    "pybind11",
]
build-backend = "scikit_build_core.build"

[project]
name = "cascadio"
version = "0.0.1"
requires-python = ">=3.7"

[project.optional-dependencies]
test = ["pytest>=6.0"]

[tool.cibuildwheel]
# only build for CPython x86_64
build = "cp*x86_64"

[tool.cibuildwheel.linux]
# build OCCT on linux from source on the manylinux image
before-all = [
'yum install -y rapidjson-devel freetype-devel fontconfig-devel',
'cd OCCT',
'git clean -xdf',
'cmake -D USE_RAPIDJSON:BOOL="ON" .',
'make -j8'
]

# point auditwheel at the OCCT libraries
repair-wheel-command = "LD_LIBRARY_PATH=/project/OCCT/lin64/gcc/lib auditwheel repair --lib-sdir . -w {dest_dir} {wheel}"
