[build-system]
requires = [
    "scikit_build_core[pyproject]",
    "pybind11",
]
build-backend = "scikit_build_core.build"

[project]
name = "cascadio"
version = "0.0.1"
requires-python = ">=3.7"

[project.optional-dependencies]
test = ["pytest"]


[tool.cibuildwheel.linux]
# build OCCT on linux from source on the manylinux image
before-all = [
'pip install ninja',
'yum install -y freetype-devel fontconfig-devel',
'cd upstream/OCCT',
'git clean -xdf',
'cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DUSE_RAPIDJSON:BOOL="ON" -D3RDPARTY_RAPIDJSON_INCLUDE_DIR="../rapidjson/include" .',
'ninja',
'mv lin64/gcc/lib . || true',
'mv lin32/gcc/lib . || true',
]

before-test = "pip install pytest"
test-command = "pytest {project}/tests"

# point auditwheel at the OCCT libraries
repair-wheel-command = "LD_LIBRARY_PATH=/project/upstream/OCCT/lin64/gcc/lib auditwheel repair --lib-sdir . -w {dest_dir} {wheel}"
