[build-system]
requires = [
    "scikit_build_core[pyproject]",
    "pybind11",
]
build-backend = "scikit_build_core.build"

[project]
name = "cascadio"
version = "0.0.1"
requires-python = ">=3.7"
authors = [{name = "Michael Dawson-Haggerty", email = "mikedh@kerfed.com"}]
license = {file = "LICENSE/LICENSE-cascadio.md"}
description = "Convert STEP files to GLB using OpenCASCADE"
keywords = ["graphics", "STEP", "GLTF"]
classifiers = [
    "Development Status :: 4 - Beta",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering",
    "Topic :: Multimedia :: Graphics",
    "Topic :: Multimedia :: Graphics :: 3D Modeling"
]
urls = {Homepage = "https://github.com/trimesh/cascadio"}

[project.readme]
file = "README.md"
content-type = "text/markdown"

[project.optional-dependencies]
tests = ["pytest", "trimesh"]

[tool.cibuildwheel]
# `yum` would need to be replaced in the `before-all`
# script before the musl linux can build OpenCASCADE
skip = "*musl*"

[tool.cibuildwheel.linux]
# build OCCT on linux from source on the manylinux image
before-all = [
'pip install ninja',
'yum install -y freetype-devel fontconfig-devel',
'cd upstream/OCCT',
'git clean -xdf',
'cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DUSE_RAPIDJSON:BOOL="ON" -D3RDPARTY_RAPIDJSON_INCLUDE_DIR="../rapidjson/include" .',
'ninja',
'mv lin64/gcc/lib . || true',
'mv lin32/gcc/lib . || true',
]

test-extras = "tests"
test-command = "pytest {project}/tests"

# point auditwheel at the OCCT libraries
repair-wheel-command = "LD_LIBRARY_PATH=/project/upstream/OCCT/lib auditwheel repair --lib-sdir . -w {dest_dir} {wheel}"
