name: Build And Release Wheels

on:
  push:
    branches:
      - main
      - release-candidate

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-14]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ilammy/msvc-dev-cmd@v1.13.0
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        with:
          output-dir: wheelhouse

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl

  upload_all:
    name: Upload To PyPi
    needs: build_wheels
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/setup-python@v4
    - uses: actions/download-artifact@v2
      with:
        name: artifact
        path: dist
    - name: Publish
      uses: pypa/gh-action-pypi-publish@v1.8.12
